# -*- coding: utf-8 -*-
"""AI Document & PDF Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXYS4MC9Kw9hQmzhSzcO93tQq2YY_ydf
"""

!pip install -q -U google-genai pypdf streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from google import genai
# import pypdf
# 
# st.set_page_config(page_title="AI Document Assistant", layout="wide")
# 
# st.title("📄 AI Document & PDF Assistant")
# st.write("Upload your PDF files and ask any questions based on their content!")
# 
# with st.sidebar:
#     st.header("Configuration")
#     api_key = st.text_input("Enter Gemini API Key", type="password")
# 
# uploaded_file = st.file_uploader("Upload a PDF document", type=["pdf"])
# 
# if uploaded_file is not None:
#     pdf_reader = pypdf.PdfReader(uploaded_file)
#     text = ""
#     for page in pdf_reader.pages:
#         extracted = page.extract_text()
#         if extracted:
#             text += extracted
# 
#     st.success(f"PDF uploaded successfully! Total pages: {len(pdf_reader.pages)}")
# 
#     user_query = st.text_input("Ask a question about your PDF:")
# 
#     if st.button("Get Answer"):
#         if not api_key:
#             st.error("Please enter your Gemini API Key in the sidebar.")
#         else:
#             try:
#                 client = genai.Client(api_key=api_key.strip())
#                 prompt = f"Context from PDF document:\n{text}\n\nQuestion: {user_query}\nAnswer:"
# 
#                 with st.spinner("Analyzing document..."):
#                     # Updated to gemini-3.6-flash as requested by the API
#                     response = client.models.generate_content(
#                         model='gemini-3.6-flash',
#                         contents=prompt,
#                     )
#                     st.write("### Answer:")
#                     st.write(response.text)
#             except Exception as e:
#                 st.error(f"Error: {e}")

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
import subprocess
import time

subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])
time.sleep(3)

print("آپ کا لائیو لنک بن رہا ہے:\n")
!./cloudflared tunnel --url http://localhost:8501